### ISSUE TITLE
Document PinOut antitamper

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [Smashing-Tech/Libsmashhit-Tools#2]
it has a more advanced antitamper than smash hit (i think)
so that when repackaged with APK Editor Studio without changing anything PinOut crashes

**Comment by knot126** [comment]
I've not tried anything, though that does not seem likely if the libs arent modified. Does apk editor studio have any errors during optimisation? If it does, that can cause an immediate crash. Otherwise it's possible it has stronger antitamper.

**Comment by H-A-M-G-E-R** [comment]
i think the optimisation isn't the problem
it's the recompiling of the decompiled smali
P.S. does making smash hit vr work on any android device involve a libsmashhit.so or libvrapi.so edit?

**Comment by knot126** [comment]
> i think the optimisation isn't the problem
> it's the recompiling of the decompiled smali

That would make sense, Smash Hit's protection also includes `classes.dex` which is (de|re)compiled (to|from) smali.

>  P.S. does making smash hit vr work on any android device involve a libsmashhit.so or libvrapi.so edit?

I tried once but failed, maybe you would have luck with this? I will probably try it soon.

https://forum.xda-developers.com/t/port-gear-vr-software-to-other-android-device.3540402/

Also, if you think you will be making more contributions I can add you to the github organisation if you want. :)

**Comment by H-A-M-G-E-R** [comment]
i cloned the smash hit apk using apk editor studio without a problem
i also tried editing the manifest file in vr but it crashes

**Comment by knot126** [comment]
> i cloned the smash hit apk using apk editor studio without a problem

What do you mean by cloned? Just repacked or also edited?

> i also tried editing the manifest file in vr but it crashes

I would really care about the VR version because I think it's a cool idea but without any way to play it it's really hard to do anything, so I've got no clue what's happening. If you want to try doing things around it though I might be able to answer questions about things that are the same with regular smash hit.

**Comment by H-A-M-G-E-R** [comment]
renaming package name
smash hit music source files? p.s. dirac/absurdium tracks fit into smash hit

**Comment by H-A-M-G-E-R** [comment]
no it's not
